spring:
  session:
    store-type: jdbc
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:tcp://localhost/~/asw
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        show_sql: true
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug
  # org.hibernate.type: trace

